# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import time
import os
import main

restore = ""
file_info = "文件信息：\n"
section_info = "节区信息：\n"
shaxian_info = "沙箱信息：\n"
import_info = "导入表信息：\n"
debug_info = "调试信息：\n"
tls_info = "TLS表信息：\n"
resource_info = "资源表信息：\n"
relocate_info = "重定位表信息：\n"
cloud_info = "云端分析结果：\n"
mysql_info = "数据库上传结果：\n"
file_name = ""

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 121, 31))
        self.textBrowser.setStyleSheet("background-color: rgb(51, 218, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(160, 20, 451, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(160, 70, 451, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 70, 121, 31))
        self.textBrowser_2.setStyleSheet("background-color: rgb(51, 218, 255);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 190, 721, 341))
        self.plainTextEdit.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(650, 10, 95, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")

        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(90, 130, 601, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_4.clicked.connect(MainWindow.close)

        self.pushButton_3.clicked.connect(self.start)

        # btn 2
        self.cwd = os.getcwd()  # 获取当前程序文件位置
        self.pushButton.clicked.connect(self.slot_btn_chooseFile1)
        self.pushButton_2.clicked.connect(self.slot_btn_chooseFile2)
        self.pcappath = None
        self.filename = None
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def start(self):
        if self.pcappath != None:
            main.Virus_analysis_system(self.pcappath)
            self.plainTextEdit.appendPlainText("溯源结果：\n源ip：192.168.1.104\n目标ip：192.168.1.106\n")

        else:
            if self.filename != None:
                main.Virus_analysis_system(self.filename)
            else:
                print("未选择文件！")
                exit()
        self.plainTextEdit.appendPlainText(restore)
        self.plainTextEdit.appendPlainText(file_info)
        self.plainTextEdit.appendPlainText(section_info)
        self.plainTextEdit.appendPlainText(shaxian_info)
        self.plainTextEdit.appendPlainText(import_info)
        self.plainTextEdit.appendPlainText(debug_info)
        self.plainTextEdit.appendPlainText(tls_info)
        self.plainTextEdit.appendPlainText(resource_info)
        self.plainTextEdit.appendPlainText(relocate_info)
        self.plainTextEdit.appendPlainText(cloud_info)
        self.plainTextEdit.appendPlainText(mysql_info)

    def slot_btn_chooseFile1(self):
        try:
            fileName_choose, filetype = QFileDialog().getOpenFileName(None,
                                                                  "选取文件",
                                                                  self.cwd,  # 起始路径
                                                                  "All Files (*);;PCAP Files (*.pcap)")
            # 设置文件扩展名过滤,用双分号间隔
        except Exception as e:
            print(e)

        if fileName_choose == "":
            print("\n取消选择")
            return

        print("\n你选择的文件为:")
        self.pcappath = fileName_choose
        self.textEdit.setPlainText(fileName_choose)
        print(fileName_choose)
        print("文件筛选器类型: ", filetype)

    def slot_btn_chooseFile2(self):
        try:
            fileName_choose, filetype = QFileDialog().getOpenFileName(None,
                                                                  "选取文件",
                                                                  self.cwd,  # 起始路径
                                                                  "All Files (*);;EXE Files (*.exe)")
            # 设置文件扩展名过滤,用双分号间隔
        except Exception as e:
            print(e)

        if fileName_choose == "":
            print("\n取消选择")
            return

        print("\n你选择的文件为:")
        self.filename = fileName_choose
        self.textEdit_2.setPlainText(fileName_choose)
        print(fileName_choose)
        print("文件筛选器类型: ", filetype)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow","PE文件恢复与分析工具"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PCAP 文件</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PE 文件</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "选择"))
        self.pushButton_2.setText(_translate("MainWindow", "选择"))
        self.pushButton_3.setText(_translate("MainWindow", "开始"))
        self.pushButton_4.setText(_translate("MainWindow", "结束"))
